### ISSUE TITLE
rails3 compatibility?

### ISSUE THREAD

**Issue by zawaideh** [hayesgm/mountain_goat#2]
from the docs, it looks like this is designed for rails 2. Would it work with rails3 as well?

**Comment by hayesgm** [comment]
I haven't tested it on Rails 3 yet.  Basically, it does Route injection for the admin interface, and those systems are unlikely to work with the new Rails 3 routing mechanisms.  That said, it hasn't been tested and is probably not too difficult to update these systems for Rails 3.

Otherwise, there's small Rails 2->3 conversations that need to do through, such as changes in ActiveRecord syntax.  I'd love a pull request from anyone with time to get these changes made.

**Comment by zawaideh** [comment]
would you want to keep simultaneous compatibility or would a seperate rails3 branch be ok?

My thoughts are to implement it as a mountable rails engine and target rails 3.2 but can hardly commit any time for rails2

**Comment by hayesgm** [comment]
A branch for Rails 3 would be best.  We can maintain Rails 2 as a bug-fix branch, but focus core development on Rails 3.

Send me a message at geoff[at]safeshepherd.com if you want some advice walking through the current code.  I would hope we can get compatibility for Rails 3 up in the next 4-6 weeks.  Most of the changes should be pretty small, basically around ActiveRecord, routing-injections, rake tasks, and other Rails-hacks that don't transfer over to Rails 3.

**Comment by lizderr** [comment]
I'd really like to use mountain-goat for my a/b testing, but I'm using rails 3.  Any update on when the rails 3 implementation might be available?

**Comment by zawaideh** [comment]
I am currently swamped and unlikely to be able to look at this anytime soon. I'd be happy to use it if anyone does implement it.
